apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base
- ingress.yaml

configMapGenerator:
- literals:
  - API_URL=http://dev-churn-api:8000
  name: churn-frontend-config

images:
- name: churn-prediction-frontend
  newName: shivamkurtarkar/churn-prediction-frontend
  newTag: ba12cbc
