apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base

images:
- name: churn-prediction-frontend
  newName: shivamkurtarkar/churn-prediction-frontend
  newTag: 8101b6e
