apiVersion: v1
kind: Service
metadata:
  name: churn-frontend
  labels:
    app: churn-frontend
spec:
  type: NodePort
  ports:
    - port: 8501
      targetPort: 8501
  selector:
    app: churn-frontend
