apiVersion: v1
kind: Service
metadata:
  name: churn-api
  labels:
    app: churn-api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
  selector:
    app: churn-api
