apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
  - ../../base

# configMapGenerator:
#   - name: model-configmap
#     files:
#       - nn_model.joblib=../../api/nn_model.joblib

images:
  - name: churn-api-image
    newTag: latest
