apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base
# - ingress.yaml

# configMapGenerator:
#   - name: model-configmap
#     files:
#       - nn_model.joblib=../../api/nn_model.joblib

images:
- name: churn-prediction-api
  newName: shivamkurtarkar/churn-prediction-api
  newTag: ba12cbc
